#消融使用目录清单


# arguments for dataset
dataset: pascal
data_root: /home/roots/DeepLearning_Linux_MD/Dataset_MD/VOC2012
nclass: 21
crop_size: 476
use_augmix: False # 控制是否进行augmix
use_cutmix: True # 控制是否进行CutMix
cutmix_ratio: 0.5 # CutMix的比例
use_augment: True  # 控制是否进行增强

# arguments for training
epochs: 60
batch_size: 6 # per GPU x 4 GPUs
lr:  0.000005
lr_multi: 40.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95
jsd_weight: 0 # 建议从 0.1 开始尝试，如 0.05, 0.1, 0.2
mse_weight: 0  # ← 启用 MSE
kl_weight: 0.0  # ← 启用 KL 散度2




# arguments for model
model: dpt
backbone: dinov2_small
lock_backbone: False
use_dropout: True # 控制是否进行dropout，12-15
fad_prob: 0.2
cd_prob: 0.3